add_newline = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncate_to_repo=false
truncation_symbol="…/"

[docker_context]
format = ""

[git_branch]
symbol = "🌱 "
truncation_length = 15
truncation_symbol = "…"
#ignore_branches = ["master", "main"]

[kubernetes]
disabled = false
format = '[⛵ $context \($namespace\)](dimmed green) '
